# URL do banco
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/veterinary_clinic?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}

# Usuario do banco
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}

# Senha
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

# JPA (Controla o que o Hibernate faz com as tabelas)
# Quando sua aplicacao inicia, ele compara suas entidades Java com o banco.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Mostrar SQL no console
spring.jpa.show-sql=true

# Formatar SQL
spring.jpa.properties.hibernate.format_sql=true
